---
title: "Project 1 Peer Feedback"
subtitle: "Math 241, Week 8"
author: "Insert Your Name Here"
format: pdf
editor: source
---

## Due: Friday, March 17th at 10pm

Instructions:

-   To turn this feedback form in, email it to the group members and CC Grayson (gwhite at reed dot edu).

-   I am not looking for a specific word count, length, or anything like that here. Just good, thoughtful, feedback that can help your peers make their project as good as it can be.

## Group Number and Names

\[Insert group number and names of group members here\]

## Summary

\[Provide a brief summary of the shiny dashboard. What does the dashboard aim to achieve? What data sources are included? What sorts of visualizations / summaries are included\]

## Minor comments

\[Provide minor comments here. These can be small things like typos, small thematic adjustments, etc.\]

## Major comments

\[Provide major comments here. These can be bigger ideas related to structure of the app, how the UI feels to use, if things are working in server correctly or not, etc. Remember, when providing constructive feedback, the best suggestions are **specific** and **actionable**. At a minimum, make specific comments when it isn't clear to you what actions might be taken to correct the problem.\]
